[package]
name = "rhythme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
bevy_egui = "0.14"
bevy-inspector-egui = "0.11.0"
bevy_framepace = "0.4.0"

[workspace]
resolver = "2"
